name: Build and Publish (Gitea)
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - name: Login to the Container registry
       run: docker login https://git.kbdharun.dev -u kbdharun -p ${{ secrets.GITEA_TOKEN }}

     - name: Build and push to GHCR
       run: |
          docker build . --tag git.kbdharun.dev/kbdharun/hello-package:latest
          docker run git.kbdharun.dev/kbdharun/hello-package:latest
          docker push git.kbdharun.dev/kbdharun/hello-package:latest
