#publish your docker image to github container registry
name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
                echo ${{secrets.TOKEN}} | docker login ghcr.io -u kbdharun --password-stdin
      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/kbdharun/hello-package:latest
          docker run ghcr.io/kbdharun/hello-package:latest
          docker push ghcr.io/kbdharun/hello-package:latest
