name: Build and Publish (Gitea)
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vanilla-os/pico:main
    permissions:
      contents: read
      packages: write

    steps:
     - name: Checkout repository
       uses: actions/checkout@v4
      
     - name: Setup Docker
       run: |
        # Add Docker's official GPG key:
        apt-get update
        apt-get install ca-certificates curl gnupg
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
        
        # Add the repository to Apt sources:
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update
        apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y

     - name: Login to the Container registry
       run: echo "${{ secrets.GITEA_TOKEN }}" | docker login git.kbdharun.dev -u kbdharun --password-stdin

     - name: Build and push to GHCR
       run: |
          docker build . --tag git.kbdharun.dev/kbdharun/hello-package:latest
          docker run git.kbdharun.dev/kbdharun/hello-package:latest
          docker push git.kbdharun.dev/kbdharun/hello-package:latest
