name: Build and Publish
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write # Allow pushing images to GHCR
      attestations: write # To create and write attestations
      id-token: write # Additional permissions for the persistence of the attestations
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        uses: docker/metadata-action@v5
        with:
          images: |
           ${{ secrets.DOCKER_USERNAME }}/hello-package
            ghcr.io/kbdharun/hello-package
            quay.io/kbdharun/hello-package
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}  
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/hello-package:latest
            ghcr.io/kbdharun/hello-package:latest
            quay.io/kbdharun/hello-package:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          provenance: false
      - name: Attest pushed image
        uses: actions/attest-build-provenance@v1
        id: attest
        with:
          subject-name: ghcr.io/kbdharun/hello-package
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: false
