name: publish
on: [push]
runs-on: ubuntu-latest
steps:
        # This is where you will update the PAT to GITHUB_TOKEN
 run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
       docker build . --tag ghcr.io/kbdharun/hello-package:latest
       docker run ghcr.io/kbdharun/hello-package:latest
       docker push ghcr.io/kbdharun/hello-package:latest
