#publish your docker image to github container registry
name: publish
on: [push]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    permissions:
     contents: read
     packages: write
    
    steps:
     - name: Checkout repository
       uses: actions/checkout@v3
       
     - name: Log in to the Container registry
       uses: docker/login-action@v2
       with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
     - name: Build and push Docker image
       run: |
          docker build . --tag ghcr.io/kbdharun/hello-package:latest
          docker run ghcr.io/kbdharun/hello-package:latest
          docker push ghcr.io/kbdharun/hello-package:latest
